on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            **Release Notes: demo-java-fx Password Generator Application**

            We are excited to announce the release of the demo-java-fx password generator application, designed to provide users with a secure and convenient way to create strong, random passwords. This application allows users to generate passwords with a customizable length—up to 16 characters—ensuring optimal security for their accounts. Built with the intuitive JavaFX framework, it features a user-friendly interface that makes password generation simple and efficient. Safeguard your digital presence with strong passwords generated at the click of a button!
          draft: false
          prerelease: false